{
 "title": "MegaRAID Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(megaraid_controller_info, instance)"
   },
   {
    "name": "controller",
    "label": "Controller RAID:",
    "query": "label_values(megaraid_pd_info{instance=~\"$node\"}, controller)"
   },
   {
    "name": "enclosure",
    "label": "Enclosure:",
    "query": "label_values(megaraid_pd_info{instance=~\"$node\"}, enclosure)"
   },
   {
    "name": "slot",
    "label": "Slot:",
    "query": "label_values(megaraid_pd_info{instance=~\"$node\"}, slot)"
   }
  ]
 },
 "panels": [
  { "title": "Raid Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Megaraid Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_healthy{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  {
   "title": "Megaraid Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_failed{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  {
   "title": "Megaraid Degraded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_degraded{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  {
   "title": "Controller Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_temperature{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  {
   "title": "Physical Drive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_physical_drives{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  {
   "title": "Virtual Drive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_virtual_drives{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  {
   "title": "Megaraid Battery Backup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_battery_backup_healthy{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  { "title": "Disk Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "PD Media Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_media_errors{instance=\"$node\",controller=\"$controller\",slot=\"$slot\"}"
    }
   ]
  },
  {
   "title": "PD Other Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_other_errors{instance=\"$node\",controller=\"$controller\",slot=\"$slot\"}"
    }
   ]
  },
  {
   "title": "PD Predictive Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_predictive_errors{instance=\"$node\",controller=\"$controller\",slot=\"$slot\"}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "megaraid_pd_drive_temperature{instance=\"$node\"}",
     "legendFormat": "{{slot}}"
    }
   ]
  },
  {
   "title": "PD Shield Counter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_shield_counter{instance=\"$node\",controller=\"$controller\",slot=\"$slot\"}"
    }
   ]
  },
  {
   "title": "PD S.M.A.R.T Alerted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_smart_alerted{instance=\"$node\",controller=\"$controller\",slot=\"$slot\"}"
    }
   ]
  },
  {
   "title": "Drive Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_drive_temperature{instance=\"$node\",controller=\"$controller\",slot=\"$slot\"}"
    }
   ]
  },
  {
   "title": "Physical Drive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_physical_drives{instance=\"$node\",controller=\"$controller\"}"
    }
   ]
  },
  {
   "title": "Device Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_device_speed_gbps{instance=\"$node\",slot=\"$slot\"}"
    }
   ]
  },
  {
   "title": "Link Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "megaraid_pd_link_speed_gbps{instance=\"$node\",slot=\"$slot\"}"
    }
   ]
  }
 ]
}